#!/usr/bin/env python3
"""Extract readable text from the Deep Learning book's pdf2htmlEX pages.

The public site serves pages generated by pdf2htmlEX.  Generic HTML-to-Markdown
conversion retains layout machinery and splits words at positioned spans.  This
extractor keeps the source's text blocks and page boundaries while dropping the
layout overlays.
"""

from __future__ import annotations

import argparse
import html
import re
from pathlib import Path

from bs4 import BeautifulSoup


def clean_block(value: str) -> str:
    value = html.unescape(value)
    value = value.replace("\u00a0", " ").replace("\u200b", "")
    value = value.replace("\ufeff", "")
    value = re.sub(r"[ \t\r\f\v]+", " ", value)
    return value.strip()


def extract(path: Path) -> str:
    soup = BeautifulSoup(path.read_text(encoding="utf-8", errors="replace"), "html.parser")
    for tag in soup.select("script, style, head, #sidebar"):
        tag.decompose()

    page_container = soup.select_one("#page-container") or soup
    pages: list[str] = []
    for page in page_container.select(".pc"):
        blocks = [clean_block(node.get_text("", strip=False)) for node in page.select(".t")]
        blocks = [block for block in blocks if block]
        if blocks:
            pages.append("\n".join(blocks))

    return "\n\n--- page boundary ---\n\n".join(pages).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("site", type=Path, help="directory containing the downloaded HTML")
    parser.add_argument("output", type=Path, help="directory for cleaned text")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    for source in sorted(args.site.rglob("*.html")):
        relative = source.relative_to(args.site).with_suffix(".txt")
        destination = args.output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(extract(source), encoding="utf-8")


if __name__ == "__main__":
    main()
